# FilePath: Scripts/badge_gen.py
# Generates Shields.io badges for build-status, TestFlight, and licence counts.
# Shields docs & YouTube walkthrough illustrate the simple REST schema. :contentReference[oaicite:10]{index=10}

import urllib.parse, urllib.request, json, os

BADGES = [
    ("build-passing",      "github/actions",      "success"),
    ("size < 200 MB",      "size",               "brightgreen"),
    ("HIPAA-ready",        "compliance",         "blue")
]

def make_badge(label, logo, color):
    q = urllib.parse.urlencode({
        "label": label,
        "message": "",
        "color": color,
        "logo": logo,
        "style": "for-the-badge"
    })
    return f"https://img.shields.io/static/v1?{q}"

def main():
    lines = ["<!---- auto-generated by badge_gen.py -->"]
    for label, logo, color in BADGES:
        lines.append(f"![{label}]({make_badge(label, logo, color)})")
    with open("Resources/README_badges.md", "w") as fh:
        fh.write(" ".join(lines))
    print("✅  Badges written to Resources/README_badges.md")

if __name__ == "__main__":
    main()
