// WhisperBridge.h
// Public Objective-C++ interface around whisper.cpp GGML backend.
// Auto-generated by AI assistant to expose speech-to-text wrapper to Swift code.

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

/// Streams speech-to-text transcription results using whisper.cpp.
@interface WhisperBridge : NSObject

- (instancetype)initWithModelAt:(NSString *)path NS_DESIGNATED_INITIALIZER;

/// Perform transcription on 16-kHz mono Float32 PCM samples.
/// @param pcm Pointer to the contiguous PCM buffer.
/// @param len Frame count (number of float samples).
/// @param lang BCP-47 language code, e.g. "en".
/// @param progress Optional incremental callback emitting intermediate text.
/// @param completion Invoked with the full transcription once finished.
- (void)transcribePCM:(float *)pcm
               length:(int)len
             language:(NSString *)lang
       progressBlock:(nullable void (^)(NSString *chunk))progress
          completion:(nullable void (^)(NSString *full))completion;

/// Release the heavy Whisper context to lower memory footprint. Implemented in category.
- (void)unload;

@end

NS_ASSUME_NONNULL_END 